name: Save Data

on:
  push:
    branches:
      - main

jobs:
  saveData:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Save data
        run: |
          curl -X POST -d "@datos.json" -H "Content-Type: application/json" https://TonyBravo2021.github.io/guardar_datos.php
